platform :ios, '15.0'
use_frameworks!

target 'ImageSlideshow_Example' do
    pod "ImageSlideshow", :path => "../"
    pod "ImageSlideshow/Alamofire", :path => "../"
    pod "ImageSlideshow/SDWebImage", :path => "../"
    pod "ImageSlideshow/Kingfisher", :path => "../"

    target 'ImageSlideshow_Tests' do
        inherit! :search_paths
    end
end
